image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Initalise terraform
    init: |
      export AWS_DEFAULT_REGION="eu-central-1"
    command: |
      terraform --version
vscode:
  extensions:
    - hashicorp.terraform